version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST_Queue=redis://redis-queue:6379
    depends_on:
      - redis-queue

  ai-server:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ai-server/.env

  redis-queue:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_queue_data:/data
    command: redis-server --appendonly yes
    container_name: redis-queue
    restart: always

volumes:
  redis_queue_data: